const REACT_ROUTER_PATH = [
    '/',
    '/main',
    '/about',
    '/gathering',
    '/gathering/:id',
    '/gathering/onetime/:id',
    '/gathering/oneyear/:id',
    '/recent-gathering-history',
    '/package',
    '/package/:id',
    '/package/onetime/:id',
    '/package/sixmonths/:id',
    '/recent-package-history',
    '/recent-package-subsc',
    '/store',
    '/store/good',
    '/store/book/:id',
    '/store/good/:id',
    '/cart',
    '/purchase',
    '/recent-order',
    '/notice',
    '/mypage',
    '/login',
    '/register',
];

export default REACT_ROUTER_PATH;
